#pragma once
#include <cstring>

typedef struct {
    const char* key;
    const unsigned char* start;
    const unsigned char* end;
    const char* partner_upper;
    const char* partner_formatted;
    const char* type_test;
} branding_entry_t;

// MAXXIMED logo symbols (generated by ESP-IDF from embedded .png.gz)
extern const unsigned char _binary_maxximed_png_gz_start[] asm("_binary_maxximed_png_gz_start");
extern const unsigned char _binary_maxximed_png_gz_end[]   asm("_binary_maxximed_png_gz_end");

const branding_entry_t* branding_get(const char* logo_key);
