idf_component_register(
    EMBED_FILES 
        "www/pages/restrict.html.gz"
        "www/pages/calibration.html.gz"
        "www/pages/settings.html.gz"
        "www/pages/ampoules.html.gz"
        "www/pages/serialnumber.html.gz"
        "www/pages/reset.html.gz"
        "www/src/bootstrap/css/bootstrap.min.css.gz"
        "www/src/bootstrap/css/bootstrap-toaster.min.css.gz"
        "www/src/bootstrap/css/bootstrap-icons.css.gz"
        "www/src/bootstrap/css/fonts/bootstrap-icons.woff.gz"
        "www/src/bootstrap/css/fonts/bootstrap-icons.woff2.gz"
        "www/src/bootstrap/js/bootstrap.min.js.gz"
        "www/src/bootstrap/js/bootstrap-toaster.min.js.gz"
        "www/src/bootstrap_datetimepicker/bootstrap.datetimepicker.min.css.gz"
        "www/src/bootstrap_datetimepicker/bootstrap.datetimepicker.min.js.gz"
        "www/src/jquery/jquery.min.js.gz"
        "www/src/chartjs/chart.min.js.gz"
        "www/src/moment/moment-with-locales.js.gz"
        "www/src/moment/moment.js.gz"
        "www/src/custom/custom.js.gz"
        "www/src/jqueryMultiLanguage/jquery.multilanguage.min.js.gz"
        "www/src/locales/es-es.json.gz"
        "www/src/locales/en-us.json.gz"
        "www/src/locales/pt-br.json.gz"
        "www/resources/baumer.png.gz"
        "www/resources/maxximed.png.gz"
        "www/resources/medcontrol.png.gz"
        "www/resources/tech_steri.png.gz"
        "www/resources/biosterons.png.gz"
)
